### PR TITLE
Add `bower-install` task

### PR DESCRIPTION
**Pull request by ericf**
This adds a task to install Bower packages.

All the other Grunt + Bower tasks didn't fit with what we needed, so this is a simple one jacked from Pure's Gruntfile.js.

### CODE REVIEW

**Comment by triptych** [comment]
Trying things now, but first off the Travis CI test failed because you need to update the number of components:

```
should export tasks
    ✗ and find 42 tasks 
        » expected 43, 
    got  42 (==) // tasks.js:25
```

**Comment by triptych** [comment]
@ericf you may want to update the help.js to mention that bower-install is available, since the other tasks in there do the same. Just a nitpick.

**Comment by triptych** [comment]
@ericf outside of the test failure, and the nitpick with the help.js --> :thumbsup:

**Comment by ericf** [comment]
What's help.js for? `grunt --help` already lists the `bower-install` task. Seems silly to duplicate that :-/

**Comment by triptych** [comment]
type grunt with no arguments - it'll run the help task and display usage information.

```
grunt
>> No --release-version passed, using version from package.json: 3.13.0-beta-1
>> No --release-build passed, using sha: cb8954c

Running "help" task
>>
>> Showing YUI specific help commands
>>

  build             Build the entire library (and npm package) locally with yogi
  release           Build a release (dist, cdn and npm)
  build-test        Build and test the entire library
  test              Test the library with yogi
  test-cli          Test the library via CLI with yogi
  travis            Perform a travis test (uses enviroment vars to determine tests)
  since-replace     Replaces @SINCE@ tokens in js files with *release-version*
  history-rollup    Creates History Rollup file (Run before history-replace)
  history-populate  Populates History files with @VERSION@ if not there already
  history-replace   Replaces @VERSION@ in History files with *release-version*
  help              Show this stuffs

>> Options:

  --release-version=<VERSION>   Pass to set the version of the release (required for a release build)
  --release-build=<BUILD>       Pass to set the build number of the release, if not passed the git sha will be used.
  --cache-build                 Cache the shifter build.

Done, without errors.
```

Like you said, since it's already in the --help then up to you if you want to update the help.js or not.

**Pull request merged**
