### PR TITLE
Adding @SINCE@ replacement to grunt task

### PR DESCRIPTION
**Pull request by triptych**
This uses the same framework as the other grunt tasks to find and replace @SINCE@ tokens. 
It takes advantage of the _release version_ argument to grunt to know what version to use.

### CODE REVIEW

**Comment by triptych** [comment]
Build fails because of the # of objects in test.  Will wait till other pull request goes through before updating tests.

**Comment by ericf** [comment]
@triptych so you want me to merge #8 first before this one?

**Comment by triptych** [comment]
Yes, please.

**Comment by ericf** [comment]
@triptych okay, I merged #8, let me know when this one is ready…

**Comment by triptych** [comment]
@ericf Ok, merged #8 and tested locally on my own repo (created history files, touched a file with `@since @SINCE@` etc. 

It's ready to go.

**Comment by ericf** [comment]
@triptych I published `0.0.15` to npm with your two PRs merged.

**Pull request merged**
